export enum BuiltInVariable {
  LOCALE = 'locale',
  CHANNEL = 'channel',
  USER_ID = 'user_id',
  SESSIONS = 'sessions',
  PLATFORM = 'platform',
  TIMESTAMP = 'timestamp',
  INTENT_CONFIDENCE = 'intent_confidence',
  LAST_UTTERANCE = 'last_utterance',
  LAST_RESPONSE = 'last_response',
  LAST_EVENT = 'last_event',
  VF_MEMORY = 'vf_memory',
  VF_CHUNKS = 'vf_chunks',
  FUNCTION_CONDITIONAL_TRANSFERS = 'function_conditional_transfers',
}
