export enum ErrorCode {
  INTEGRATION_INVALID_CREDENTIALS = 'INTEGRATION_INVALID_CREDENTIALS',
  INTEGRATION_RESOURCE_NOT_FOUND = 'INTEGRATION_RESOURCE_NOT_FOUND',

  BILLING_QUOTA_EXCEEDED = 'BILLING_QUOTA_EXCEEDED',
  BILLING_PLAN_NOT_ALLOWED = 'BILLING_PLAN_NOT_ALLOWED',
}
