version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

# Reusable YAML chunks
defaults:
  tag_filters: &tag_filters
    tags:
      only: /^@voiceflow/.*@[0-9]*(\.[0-9]*)*$/

workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          filters:
            <<: *tag_filters
          base-revision: master
          config-path: .circleci/continue-config.yml
          mapping: |
            package.json build-all true
            yarn.lock build-all true
