version: 2.1

# Reusable YAML chunks
defaults:
  autorebase_filters: &autorebase_filters
    branches:
      ignore:
        - /rebase-pull-request-.*/
        - /cherry-pick-rebase-pull-request-.*/

orbs:
  vfcommon: voiceflow/common@0.0.177
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build-and-test:
    executor: vfcommon/default-executor
    steps:
      - checkout
      - vfcommon/install_node_modules:
          avoid_post_install_scripts: false
      - vfcommon/build
      - vfcommon/lint_report
      - vfcommon/dependency_tests:
          step_name: Dependency Tests
      - vfcommon/unit_tests
      - sonarcloud/scan

workflows:
  test-and-release:
    jobs:
      - build-and-test:
          context: dev-test
          filters:
            <<: *autorebase_filters

      - vfcommon/release_monorepo:
          avoid_post_install_scripts: false
          ssh_key: "94:fb:dc:e2:30:96:9d:61:f5:6f:95:c2:32:20:f7:37"
          context: dev-test
          requires:
            - build-and-test
          filters:
            branches:
              only: master
