import { BuiltinSlot } from '@voiceflow/common';

import { Locale as L } from './locales';

// https://cloud.google.com/dialogflow/es/docs/reference/system-entities
// deprecated entities have NOT been included in the ENUM
export enum SlotType {
  DATE_TIME = '@sys.date-time',
  DATE = '@sys.date',
  DATE_PERIOD = '@sys.date-period',
  TIME = '@sys.time',
  TIME_PERIOD = '@sys.time-period',
  NUMBER = '@sys.number',
  CARDINAL = '@sys.cardinal',
  ORDINAL = '@sys.ordinal',
  NUMBER_INTEGER = '@sys.number-integer',
  NUMBER_SEQUENCE = '@sys.number-sequence',
  FLIGHT_NUMBER = '@sys.flight-number',
  UNIT_AREA = '@sys.unit-area',
  UNIT_CURRENCY = '@sys.unit-currency',
  UNIT_LENGTH = '@sys.unit-length',
  UNIT_SPEED = '@sys.unit-speed',
  UNIT_VOLUME = '@sys.unit-volume',
  UNIT_WEIGHT = '@sys.unit-weight',
  UNIT_INFORMATION = '@sys.unit-information',
  PERCENTAGE = '@sys.percentage',
  TEMPERATURE = '@sys.temperature',
  DURATION = '@sys.duration',
  AGE = '@sys.age',
  CURRENCY_NAME = '@sys.currency-name',
  UNIT_AREA_NAME = '@sys.unit-area-name',
  UNIT_LENGTH_NAME = '@sys.unit-length-name',
  UNIT_SPEED_NAME = '@sys.unit-speed-name',
  UNIT_VOLUME_NAME = '@sys.unit-volume-name',
  UNIT_WEIGHT_NAME = '@sys.unit-weight-name',
  UNIT_INFORMATION_NAME = '@sys.unit-information-name',
  ADDRESS = '@sys.address',
  ZIP_CODE = '@sys.zip-code',
  GEO_CAPITAL = '@sys.geo-capital',
  GEO_COUNTRY = '@sys.geo-country',
  GEO_COUNTRY_CODE = '@sys.geo-country-code',
  GEO_CITY = '@sys.geo-city',
  GEO_STATE = '@sys.geo-state',
  PLACE_ATTRACTION = '@sys.place-attraction',
  AIRPORT = '@sys.airport',
  LOCATION = '@sys.location',
  EMAIL = '@sys.email',
  PHONE_NUMBER = '@sys.phone-number',
  PERSON = '@sys.person',
  MUSIC_ARTIST = '@sys.music-artist',
  MUSIC_GENRE = '@sys.music-genre',
  COLOR = '@sys.color',
  LANGUAGE = '@sys.language',
  ANY = '@sys.any',
  URL = '@sys.url',
}

export const BUILT_IN_SLOTS: BuiltinSlot<SlotType, L>[] = [
  {
    type: SlotType.DATE_TIME,
    label: 'DateTime',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
      L.UK,
    ],
  },
  {
    type: SlotType.DATE,
    label: 'Date',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
      L.UK,
    ],
  },
  {
    type: SlotType.DATE_PERIOD,
    label: 'DatePeriod',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
      L.UK,
    ],
  },
  {
    type: SlotType.TIME,
    label: 'Time',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
      L.UK,
    ],
  },
  {
    type: SlotType.TIME_PERIOD,
    label: 'TimePeriod',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
      L.UK,
    ],
  },
  {
    type: SlotType.NUMBER,
    label: 'Number',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
      L.UK,
    ],
  },
  {
    type: SlotType.CARDINAL,
    label: 'Cardinal',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.ORDINAL,
    label: 'Ordinal',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.NUMBER_INTEGER,
    label: 'NumberInteger',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.NUMBER_SEQUENCE,
    label: 'NumberSequence',
    immutable: true,
    locales: [L.EN],
  },
  {
    type: SlotType.FLIGHT_NUMBER,
    label: 'FlightNumber',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.IT, L.JA, L.KO, L.PT, L.PT_BR, L.RU, L.ES, L.UK],
  },
  {
    type: SlotType.UNIT_AREA,
    label: 'UnitArea',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_CURRENCY,
    label: 'UnitCurrency',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.HI, L.ID, L.IT, L.JA, L.KO, L.NO, L.PL, L.PT_BR, L.RU, L.ES, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_LENGTH,
    label: 'UnitLength',
    immutable: true,
    locales: [L.EN, L.NL, L.FR, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_SPEED,
    label: 'UnitSpeed',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_VOLUME,
    label: 'UnitVolume',
    immutable: true,
    locales: [L.EN, L.NL, L.DE, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_WEIGHT,
    label: 'UnitWeight',
    immutable: true,
    locales: [L.EN, L.NL, L.DE, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_INFORMATION,
    label: 'UnitInformation',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.PERCENTAGE,
    label: 'Percentage',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.FR, L.DE, L.IT, L.RU, L.ES],
  },
  {
    type: SlotType.TEMPERATURE,
    label: 'Temperature',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.DURATION,
    label: 'Duration',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.FR, L.DE, L.IT, L.JA, L.RU, L.ES],
  },
  {
    type: SlotType.AGE,
    label: 'Age',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.FR, L.IT],
  },
  {
    type: SlotType.CURRENCY_NAME,
    label: 'CurrencyName',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.HI, L.ID, L.IT, L.JA, L.KO, L.NO, L.PL, L.PT_BR, L.RU, L.ES, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_AREA_NAME,
    label: 'UnitAreaName',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_LENGTH_NAME,
    label: 'UnitLengthName',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_SPEED_NAME,
    label: 'UnitSpeedName',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_VOLUME_NAME,
    label: 'UnitVolumeName',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_WEIGHT_NAME,
    label: 'UnitWeightName',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.UNIT_INFORMATION_NAME,
    label: 'UnitInformationName',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.ADDRESS,
    label: 'Address',
    immutable: true,
    locales: [L.EN, L.ZH_CN, L.FR, L.DE, L.IT, L.JA, L.RU, L.ES],
  },
  {
    type: SlotType.ZIP_CODE,
    label: 'ZipCode',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
    ],
  },
  {
    type: SlotType.GEO_CAPITAL,
    label: 'GeoCapital',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.RU, L.ES, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.GEO_COUNTRY,
    label: 'GeoCountry',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
    ],
  },
  {
    type: SlotType.GEO_COUNTRY_CODE,
    label: 'GeoCountryCode',
    immutable: true,
    locales: [L.EN],
  },
  {
    type: SlotType.GEO_CITY,
    label: 'GeoCity',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
    ],
  },
  {
    type: SlotType.GEO_STATE,
    label: 'GeoState',
    immutable: true,
    locales: [L.EN, L.NL, L.FR, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.ES, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.PLACE_ATTRACTION,
    label: 'PlaceAttraction',
    immutable: true,
    locales: [L.EN, L.FR, L.JA],
  },
  {
    type: SlotType.AIRPORT,
    label: 'Airport',
    immutable: true,
    locales: [L.EN],
  },
  {
    type: SlotType.LOCATION,
    label: 'Location',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.FR, L.DE, L.IT, L.JA, L.PT, L.PT_BR, L.RU, L.ES],
  },
  {
    type: SlotType.EMAIL,
    label: 'Email',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.IT, L.JA, L.PT, L.PT_BR, L.RU, L.ES, L.UK],
  },
  {
    type: SlotType.PHONE_NUMBER,
    label: 'PhoneNumber',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.IT, L.JA, L.PT, L.PT_BR, L.RU, L.ES, L.UK],
  },
  {
    type: SlotType.PERSON,
    label: 'Person',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.HI, L.ID, L.IT, L.JA, L.KO, L.NO, L.PL, L.PT_BR, L.RU, L.ES, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.MUSIC_ARTIST,
    label: 'MusicArtist',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.HI, L.ID, L.IT, L.JA, L.KO, L.NO, L.PL, L.PT_BR, L.RU, L.ES, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.MUSIC_GENRE,
    label: 'MusicGenre',
    immutable: true,
    locales: [L.EN, L.NL, L.HI, L.ID, L.KO, L.NO, L.PL, L.PT_BR, L.ES, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.COLOR,
    label: 'Color',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.HI, L.ID, L.IT, L.JA, L.KO, L.NO, L.PL, L.PT_BR, L.RU, L.ES, L.SV, L.TH, L.TR],
  },
  {
    type: SlotType.LANGUAGE,
    label: 'Language',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
    ],
  },
  {
    type: SlotType.ANY,
    label: 'Any',
    immutable: true,
    locales: [
      L.EN,
      L.ZH_HK,
      L.ZH_CN,
      L.ZH_TW,
      L.NL,
      L.FR,
      L.DE,
      L.HI,
      L.ID,
      L.IT,
      L.JA,
      L.KO,
      L.NO,
      L.PL,
      L.PT,
      L.PT_BR,
      L.RU,
      L.ES,
      L.SV,
      L.TH,
      L.TR,
      L.UK,
    ],
  },
  {
    type: SlotType.URL,
    label: 'URL',
    immutable: true,
    locales: [L.EN, L.ZH_HK, L.ZH_CN, L.ZH_TW, L.NL, L.FR, L.DE, L.IT, L.JA, L.KO, L.PT, L.PT_BR, L.RU, L.ES, L.UK],
  },
];
